lead_seconds: 300
tick_seconds: 20

actions:
  # - name: station_id
  #   action: static
  #   lane: duck
  #   every: "15m"
  #   params: { dir: station_ids, daypart: true, select: random }

  - name: short_stories
    action: static
    lane: next
    every: "2h"
    params: { dir: short_stories, select: shuffle }

  # - name: news
  #   action: news
  #   lane: takeover
  #   time: "19:45"
  #   params:
  #     country: us
  #     category: general
  #     count: 5

  # - name: sport
  #   action: news
  #   lane: takeover
  #   time: "19:50"
  #   params:
  #     country: us
  #     category: sports
  #     count: 5
