lead_seconds: 300
tick_seconds: 2
liquidsoap_addr: "127.0.0.1:1234"


schedules:
  - name: short_stories
    lane: next
    lead: 3
    every: "1m"
#    time: "10:0"
    select: random
    action:
      type: static
      dir: short_stories


  - name: testtesttest
    lane: takeover
    lead: 10
    every: "30s"
    select: shuffle
    action:
      type: static
      dir: short_stories

#  - name: my_channel
#    lane: duck
#    lead: 120
#    every: "30m"
#    select: shuffle
#    action:
#      type: youtube
#      url: "https://www.youtube.com/@SomeChannel"
#      cache: media/cache
