tick_seconds: 10
liquidsoap_addr: "127.0.0.1:1234"


schedules:

  - name: calm
    lane: next
    lead: 300
    time: "07:00"
    select: shuffle
    action:
      type: youtube
      url: "https://www.youtube.com/channel/UChSpME3QaSFAWK8Hpmg-Dyw"
      cache: content/media/cache


  - name: coffee_break_german
    lane: next
    lead: 300
    time: "17:00"
    select: sequential
    action:
      type: youtube
      url: "https://www.youtube.com/@coffeebreakgerman"
      cache: content/media/cache


  - name: history_of_philosophy
    lane: next
    lead: 300
    time: "10:00"
    select: sequential
    action:
      type: youtube
      url: "https://www.youtube.com/playlist?list=PL713WgO1oJMSVClLqywLoEHuPp0x5itfU"
      cache: content/media/cache


  - name: ketab_baz
    lane: next
    lead: 300
    time: "12:00"
    select: shuffle
    action:
      type: youtube
      url: "https://www.youtube.com/channel/UC5HP2dpYw4Lbaxpc6bJ1jMQ"
      cache: content/media/cache


  - name: great_courses
    lane: next
    lead: 300
    time: "14:00"
    select: shuffle
    action:
      type: youtube
      url: "https://www.youtube.com/@TheGreatCourses"
      cache: content/media/cache


  - name: closer_to_truth
    lane: next
    lead: 300
    time: "18:00"
    select: shuffle
    action:
      type: youtube
      url: "https://www.youtube.com/@CloserToTruthTV"
      cache: content/media/cache


  - name: funniest_comedy
    lane: next
    lead: 300
    time: "21:00"
    select: random
    action:
      type: youtube
      url: "https://www.youtube.com/@funniestevercomedy"
      cache: content/media/cache


  - name: hafez
    lane: next
    lead: 60
    time: "15:00"
    select: shuffle
    action:
      type: static
      dir: content/radio/Hafez


  - name: blinkist
    lane: next
    lead: 60
    time: "10:00"
    select: sequential
    action:
      type: static
      dir: content/radio/blinkist


  - name: fa_stories
    lane: next
    lead: 60
    time: "16:00"
    select: shuffle
    action:
      type: static
      dir: content/radio/fa_stories


  - name: poetry
    lane: next
    lead: 60
    time: "19:00"
    select: shuffle
    action:
      type: static
      dir: content/radio/poetry


  - name: short_stories
    lane: next
    lead: 60
    time: "20:00"
    select: sequential
    action:
      type: static
      dir: content/radio/short_stories
